image: Visual Studio 2017
platform:
  - x64

clone_folder: c:\gopath\src\github.com\kittycash\kittycash

branches:
  only:
    - master

environment:
  GOPATH: c:\gopath
  GOX_OUTPUT: .gox_output

cache:
  - 'electron\node_modules'
  - '%LOCALAPPDATA%\Yarn'
  - '%USERPROFILE%\.electron'

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/gz-c/gox
  - ps: Install-Product node 8 x64

build_script:
  - cd electron
  - yarn
  - ps: bash ./build.sh 'windows/amd64 windows/386'
  - ps: ls release\
  - ps: cd ..

after_build:
  - ps: 7z a kittycash.zip C:\gopath\src\github.com\kittycash\kittycash\electron\release\*
  - ps: ls *.zip

test: off

artifacts:
  - path: kittycash.zip
    name: published
  

# deploy to github
deploy:
  provider: GitHub
  auth_token:
    secure: Wxdp9aPViQIEoVk2Bnz/Kjx2pcp29C356HI8TJBYNgYkiI0IJj3ptA1u649OwJEZ
  artifact: kittycash.zip
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

# deploy:
#   provider: S3
#   access_key_id: $(AWS_ACCESS_KEY_ID)
#   secret_access_key: $(AWS_SECRET_ACCESS_KEY)
#   bucket: $(AWS_BUCKET)
#   region: $(AWS_REGION)
#   folder: wallet
#   artifact: published
#   unzip: true
#   set_public: true
#   on:
#     branch: master


notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
